on:
  push:
    branches:
      - main
name: Deploy Biare_quarto on push
jobs:
  web-deploy:
    name: Deploy web
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./biare_quarto/
#       server-dir: ${{ secrets.FTP_DIRECTORY }}
